import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script
          type="text/javascript"
          src="https://static.zdassets.com/zendesk_app_framework_sdk/2.0/zaf_sdk.min.js"
          strategy="beforeInteractive"
        />
        {children}
      </body>
    </html>
  );
}
